name: skill_link_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.4
  riverpod_annotation: ^3.0.3
  supabase_flutter: ^2.10.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
